apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "ds-balancer-rolebinding") }}
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "ds-balancer-sa") }}
  namespace: {{ include "ds.namespace" . | quote }}
roleRef:
  kind: Role
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "ds-balancer-role") }}
  apiGroup: rbac.authorization.k8s.io
