{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "ds-docs-rolebinding") }}
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
    {{- if .Values.commonAnnotations }}
    {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "ds.serviceAccountName" . }}
  namespace: {{ include "ds.namespace" . | quote }}
roleRef:
  kind: Role
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "ds-docs-role") }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
