{{- if .Values.upgrade.job.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ds-clear-previous-versions-rolebinding
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: ds-clear-previous-versions-sa
  namespace: {{ include "ds.namespace" . | quote }}
roleRef:
  kind: Role
  name: ds-clear-previous-versions-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
