{{- if .Values.upgrade.job.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ds-clear-previous-versions-role
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["documentserver"]
  verbs: ["get"]
{{- end }}
