{{- if eq (include "balancer.svc.create" .) "true" }}
kind: Service
apiVersion: v1
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "docs-balancer") }}
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if or .Values.commonAnnotations .Values.customBalancer.service.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.customBalancer.service.annotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "docs-balancer") }}
    {{- if .Values.commonLabels }}
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.customBalancer.service.port }}
      targetPort: {{ .Values.customBalancer.containerPorts.http }}
  type: {{ .Values.customBalancer.service.type }}
  {{- if .Values.customBalancer.sessionAffinity }}
  sessionAffinity: {{ .Values.customBalancer.service.sessionAffinity }}
  {{- if .Values.customBalancer.service.sessionAffinityConfig }}
  {{- with .Values.customBalancer.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
