kind: Service
apiVersion: v1
metadata:
  name: documentserver
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if or .Values.commonAnnotations .Values.service.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.service.annotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: documentserver
    {{- if .Values.commonLabels }}
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.documentserver.proxy.containerPorts.http }}
    {{- if .Values.documentserver.rabbitmq.metrics.enabled }}
    - name: amqp-metrics
      protocol: TCP
      port: {{ .Values.documentserver.rabbitmq.metrics.port }}
      targetPort: {{ .Values.documentserver.rabbitmq.metrics.port }}
    {{- end }}
    {{- if .Values.documentserver.postgresql.metrics.enabled }}
    - name: psql-metrics
      port: {{ .Values.documentserver.postgresql.metrics.port }}
      targetPort: {{ .Values.documentserver.postgresql.metrics.port }}
    {{- end }}
  type: {{ .Values.service.type }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- if .Values.service.sessionAffinityConfig }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
