{{- if .Values.upgrade.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "pre-upgrade") }}
  namespace: {{ include "ds.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "upgrade") }}
    {{- if .Values.commonLabels }}
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if or .Values.commonAnnotations .Values.upgrade.job.annotations }}
    {{- $dictValue := default .Values.commonAnnotations .Values.upgrade.job.annotations }}
    {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "upgrade") }}
        {{- if .Values.commonLabels }}
        {{- include "ds.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.upgrade.job.podAnnotations }}
      annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.upgrade.job.podAnnotations "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "ds-balancer-sa") }}
      {{- if .Values.upgrade.job.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.upgrade.job.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.upgrade.job.customPodAntiAffinity .Values.upgrade.job.podAffinity .Values.upgrade.job.nodeAffinity }}
      affinity:
        {{- with .Values.upgrade.job.customPodAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.upgrade.job.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.upgrade.job.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.upgrade.job.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.upgrade.job.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.upgrade.job.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.upgrade.job.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: ds-service-files
          persistentVolumeClaim:
            claimName: {{ include "ds.pvc.name" (list . .Values.persistence.existingClaim "ds-service-files") }}
        - name: clear-previous-versions
          configMap:
            name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "pre-upgrade") }}
            defaultMode: 0755
      containers:
        - name: pre-upgrade
          image: {{ .Values.upgrade.job.image.repository }}:{{ .Values.upgrade.job.image.tag }}
          imagePullPolicy: {{ .Values.upgrade.job.image.pullPolicy }}
          {{- if .Values.upgrade.job.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.upgrade.job.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.upgrade.job.resources | nindent 12 }}
          env:
          - name: PRODUCT_NAME
            value: {{ .Values.product.name | quote }}
          - name: DS_DEPLOYMENT_NAME
            value: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "documentserver") }}
          - name: DS_EP_NAME
            value: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "documentserver") }}
          volumeMounts:
          - name: ds-service-files
            mountPath: /var/lib/{{ .Values.product.name }}/documentserver/App_Data/cache/files
          - name: clear-previous-versions
            mountPath: /scripts/pre_upgrade.py
            subPath: pre_upgrade.py
          command: ['python', '/scripts/pre_upgrade.py']
      restartPolicy: Never
{{- end }}
