{{- if .Values.delete.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "pre-delete") }}
  namespace: {{ include "ds.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "delete") }}
    {{- if .Values.commonLabels }}
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if or .Values.commonAnnotations .Values.delete.job.annotations }}
    {{- $dictValue := default .Values.commonAnnotations .Values.delete.job.annotations }}
    {{- include "ds.annotations.commonAnnotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "delete") }}
        {{- if .Values.commonLabels }}
        {{- include "ds.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.delete.job.podAnnotations }}
      annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.delete.job.podAnnotations "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "ds-balancer-sa") }}
      {{- if .Values.delete.job.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.delete.job.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.delete.job.customPodAntiAffinity .Values.delete.job.podAffinity .Values.delete.job.nodeAffinity }}
      affinity:
        {{- with .Values.delete.job.customPodAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.delete.job.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.delete.job.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.delete.job.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.delete.job.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.delete.job.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.delete.job.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: stop-shards-scripts
          configMap:
            name: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "pre-delete") }}
            defaultMode: 0755
      {{- with .Values.delete.job.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pre-delete
          image: {{ .Values.delete.job.image.repository }}:{{ .Values.delete.job.image.tag }}
          imagePullPolicy: {{ .Values.delete.job.image.pullPolicy }}
          {{- if .Values.delete.job.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.delete.job.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.delete.job.resources | nindent 12 }}
          env:
          - name: DS_EP_NAME
            value: {{ include "ds.resources.name" (list . .Values.commonNameSuffix "documentserver") }}
          volumeMounts:
          - name: stop-shards-scripts
            mountPath: /scripts/pre_delete.py
            subPath: pre_delete.py
          command: ['python', '/scripts/pre_delete.py']
      restartPolicy: Never
{{- end }}
