apiVersion: v1
kind: ConfigMap
metadata:
  name: balancer-probes
  namespace: {{ include "ds.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "ds.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "ds.annotations.commonAnnotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
{{ (.Files.Glob "sources/scripts/balancer_probes.py").AsConfig | indent 2 }}
